map/urls.py
from django.urls import path
from map import views

app_name = 'map'

urlpatterns = [
    path("", views.DailyReadingView.as_view(), name="home"),
    path("livedata/<live>/", views.DailyReadingView.as_view(), name="livedata"),
    path("historical/", views.HistoricalReadingView.as_view(), name="historical"),
    path("livesignal/", views.LiveSignalView.as_view(), name="livesignal"),
    
    
]

map/models.py
from django.db import models

    
class Sensors(models.Model):
    sensor = models.CharField(max_length=122)
    latitude = models.FloatField()
    longitude = models.FloatField()
    color = models.CharField(max_length=50, default='red')
    sensor_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.sensor}_{self.color}:{self.longitude}_{self.latitude}'
    
    class Meta:
        ordering = ['-sensor_created']
        get_latest_by = ['sensor_created']
        
    
class SensorReadings(models.Model):
    sensor = models.ForeignKey(Sensors, on_delete=models.CASCADE)
    temperature = models.FloatField()
    pressure = models.FloatField()
    steam_injection = models.FloatField()
    reading_created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f'{self.sensor}'
    
    class Meta:
        ordering = ['-reading_created']
        get_latest_by = ['reading_created']

map/views.py
from django.views.generic.base import TemplateView
import folium
from folium import plugins
from map.models import Sensors, SensorReadings
from .utils import custom_tile_layers, INDUSTRIAL_SITE_LATITUDE, INDUSTRIAL_SITE_LONGITUDE
from datetime import date
from django.db.models import Avg, Max


class DailyReadingView(TemplateView):
    template_name = 'map/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sensors = Sensors.objects.all()
        context['today_date'] = date.today()
        
        # Here I grab the client's requests
        date_from_client = self.request.GET.get('day')
        aggregation_from_client = self.request.GET.get('aggregation')
        get_live_data = self.kwargs.get('live', False)
               
               
        # INDUSTRIAL SITE
        m = folium.Map(
            location=[INDUSTRIAL_SITE_LONGITUDE, INDUSTRIAL_SITE_LATITUDE], 
            tiles=None, 
            zoom_start=9, 
            control_scale=True,            
            )

        # Here, I am adding Custom tile layers
        for tile_layer in custom_tile_layers:
            folium.TileLayer(tile_layer["url"], name=tile_layer["name"], attr=tile_layer["attr"], control=True).add_to(m)

        # Here, I am adding LocateControl to find user's location
        plugins.LocateControl().add_to(m)

        # Here, I am adding Draw control for drawing on the map
        plugins.Draw(export=True, filename='data.geojson', position='topleft').add_to(m)

        # Here, I am adding MeasureControl for measuring distances and areas
        plugins.MeasureControl(position='topright', primary_length_unit='meters',
                              secondary_length_unit='miles', primary_area_unit='sqmeters', secondary_area_unit='acres').add_to(m)
        
        # Here, I am checking if readings are available for the day requested by client
        readings_are_available_for_today = SensorReadings.objects.filter(reading_created__date=date_from_client)
        
        # Here, I am creating empty lists for the heatmaps
        heat_data_temperature = []
        heat_data_pressure = []
        heat_data_steam_injection = []
        
        if get_live_data:
            for sensor in sensors:
                try:
                    live_readings = SensorReadings.objects.filter(sensor=sensor).latest()
                    # Here, I am appending the data in the format [longitude, latitude, reading ]
                    heat_data_temperature.append([sensor.longitude, sensor.latitude, live_readings.temperature])
                    heat_data_pressure.append([ sensor.longitude, sensor.latitude, live_readings.pressure])
                    heat_data_steam_injection.append([sensor.longitude, sensor.latitude, live_readings.steam_injection])
                    
                    # Here, I am adding markers for the sensors
                    coordinates = (sensor.longitude, sensor.latitude)
                    folium.Marker(coordinates, popup=sensor.sensor, tooltip=sensor.sensor, draggable=True).add_to(m)
                    
                except SensorReadings.DoesNotExist:
                    pass
                
            # Here, I am adding heatmaps for temperature, pressure, and steam injection
            plugins.HeatMap(heat_data_temperature, name='Temperature Heatmap', min_opacity=0.0,
                gradient={0.4: 'green', 0.6: 'yellow', 1: 'red'}
                ).add_to(m)
            plugins.HeatMap(heat_data_pressure, name='Pressure Heatmap', min_opacity=0.0,
                gradient={0.4: 'blue', 0.6: 'lime', 1: 'red'}
                ).add_to(m)
            plugins.HeatMap(heat_data_steam_injection, name='Steam Injection Heatmap', min_opacity=0.0,
                gradient={0.4: 'orange', 0.6: 'red'}
                ).add_to(m)
    
        elif readings_are_available_for_today:

            for sensor in sensors:
                if aggregation_from_client == 'average':
                    today_readings = readings_are_available_for_today.filter(sensor=sensor).aggregate(Avg('temperature'), Avg('pressure'), Avg('steam_injection'))

                    # Here, I am appending the data in the format [longitude, latitude, reading ]
                    heat_data_temperature.append([sensor.longitude, sensor.latitude, today_readings['temperature__avg'] or 0])
                    heat_data_pressure.append([ sensor.longitude, sensor.latitude, today_readings['pressure__avg'] or 0])
                    heat_data_steam_injection.append([sensor.longitude, sensor.latitude, today_readings['steam_injection__avg'] or 0 ])
                
                    # Here, I am adding markers for the sensors
                    coordinates = (sensor.longitude, sensor.latitude)
                    folium.Marker(coordinates, popup=sensor.sensor, tooltip=sensor.sensor, draggable=True).add_to(m)
                
                elif aggregation_from_client == 'maximum':            
                    today_readings = readings_are_available_for_today.filter(sensor=sensor).aggregate(Max('temperature'), Max('pressure'), Max('steam_injection'))

                    # Here, I am appending the data in the format [longitude, latitude, reading ]
                    heat_data_temperature.append([sensor.longitude, sensor.latitude, today_readings['temperature__max'] or 0])
                    heat_data_pressure.append([ sensor.longitude, sensor.latitude, today_readings['pressure__max'] or 0])
                    heat_data_steam_injection.append([sensor.longitude, sensor.latitude, today_readings['steam_injection__max'] or 0 ])
                
                    # Here, I am adding markers for the sensors
                    coordinates = (sensor.longitude, sensor.latitude)
                    folium.Marker(coordinates, popup=sensor.sensor, tooltip=sensor.sensor, draggable=True).add_to(m)
            
            # Here, I am adding heatmaps for temperature, pressure, and steam injection
            plugins.HeatMap(heat_data_temperature, name='Temperature Heatmap', min_opacity=0.0,
                gradient={0.4: 'green', 0.6: 'yellow', 1: 'red'}
                ).add_to(m)
            plugins.HeatMap(heat_data_pressure, name='Pressure Heatmap', min_opacity=0.0,
                gradient={0.4: 'blue', 0.6: 'lime', 1: 'red'}
                ).add_to(m)
            plugins.HeatMap(heat_data_steam_injection, name='Steam Injection Heatmap', min_opacity=0.0,
                gradient={0.4: 'orange', 0.6: 'red'}
                ).add_to(m)

        else:
            context['no_reading_message_to_client'] = "No reading available for this day"
        
        # LayerControl switch
        folium.LayerControl().add_to(m)        
        
        context['map'] = m._repr_html_()
        
        return context


class LiveSignalView(TemplateView):
    template_name = 'map/livesignal.html'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sensors = Sensors.objects.all()
        context['today_date'] = date.today()
        
        # INDUSTRIAL SITE
        m = folium.Map(
            location=[INDUSTRIAL_SITE_LONGITUDE, INDUSTRIAL_SITE_LATITUDE], 
            tiles=None, 
            zoom_start=9, 
            control_scale=True,            
            )

        # Here, I am adding Custom tile layers
        for tile_layer in custom_tile_layers:
            folium.TileLayer(tile_layer["url"], name=tile_layer["name"], attr=tile_layer["attr"], control=True).add_to(m)

        # Here, I am adding LocateControl to find user's location
        plugins.LocateControl().add_to(m)

        # Here, I am adding Draw control for drawing on the map
        plugins.Draw(export=True, filename='data.geojson', position='topleft').add_to(m)

        # Here, I am adding MeasureControl for measuring distances and areas
        plugins.MeasureControl(position='topright', primary_length_unit='meters',
                              secondary_length_unit='miles', primary_area_unit='sqmeters', secondary_area_unit='acres').add_to(m)
        
                
        # Here, I am creating empty lists for the heatmaps
        heat_data_temperature = []
        heat_data_pressure = []
        heat_data_steam_injection = []
        
        
        for sensor in sensors:
            try:
                live_readings = SensorReadings.objects.filter(sensor=sensor).latest()
                # Here, I am appending the data in the format [longitude, latitude, reading ]
                heat_data_temperature.append([sensor.longitude, sensor.latitude, live_readings.temperature])
                heat_data_pressure.append([ sensor.longitude, sensor.latitude, live_readings.pressure])
                heat_data_steam_injection.append([sensor.longitude, sensor.latitude, live_readings.steam_injection])
                
                # Here, I am adding markers for the sensors
                coordinates = (sensor.longitude, sensor.latitude)
                folium.Marker(coordinates, popup=sensor.sensor, tooltip=sensor.sensor, draggable=True).add_to(m)
                
            except SensorReadings.DoesNotExist:
                pass
            
        # Here, I am adding heatmaps for temperature, pressure, and steam injection
        plugins.HeatMap(heat_data_temperature, name='Temperature Heatmap', min_opacity=0.0,
            gradient={0.4: 'green', 0.6: 'yellow', 1: 'red'}
            ).add_to(m)
        plugins.HeatMap(heat_data_pressure, name='Pressure Heatmap', min_opacity=0.0,
            gradient={0.4: 'blue', 0.6: 'lime', 1: 'red'}
            ).add_to(m)
        plugins.HeatMap(heat_data_steam_injection, name='Steam Injection Heatmap', min_opacity=0.0,
            gradient={0.4: 'orange', 0.6: 'red'}
            ).add_to(m)
        
        # LayerControl switch
        folium.LayerControl().add_to(m)        
        
        context['map'] = m._repr_html_()

map/templates/map/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">


{% block title %}

{% endblock %}



<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Permissions-Policy" content="interest-cohort=()">

<!-- google fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;400&display=swap" rel="stylesheet">

<!-- jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<!-- bootstrap icons -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

<!-- jqueryUI -->
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- CSS AND JS files -->
{% load static %}
<link rel="stylesheet" type="text/css" href= "{% static 'map/ss.css' %}"/>
<script type="text/javascript" src="{% static 'map/mains.js' %}"></script>

</head>
<body>
{% block body%}
</body>


{% endblock %}


<div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm justify-content-center">
<a class="navbar-brand" href="{% url 'map:home' %}">
            <img src="{% static "" %}map/pdo-logo.jpg" alt="pdo" width="193">
</a>

<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>


<div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
    

<ul class="navbar-nav justify-content-center">

<li class="nav-item">
<a class="nav-link text-primary" href="{% url 'map:home' %}">Daily Reading</a>
</li>

<li class="nav-item">
    <a class="nav-link text-primary" href="{% url 'map:historical' %}">Historical Reading</a>
    </li>

    <li class="nav-item">
        <a class="nav-link text-primary" href="{% url 'map:livesignal' %}">Live Signal</a>
        </li>

</ul>
</div>
</nav>
</div>

{% block content %}


{% endblock %}

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


</html>

map/templates/map/historical.html
{% extends 'map/base.html' %}

{% block title %}
<title>Historical</title>
{% endblock %}

{% block content %}

<div class="container text-center mt-4">

  <div class="row justify-content-center">
    <div class="col-md-12">
      <p class="display-6 text-primary">Industrial Site Geospatial Historical Data</p> 
    </div>

  </div> <!-- row -->
 
<hr>

<div class="row d-flex mt-5 justify-content-center p-1 bg-light">
  <div class="col-md-4 border bg-white shadow-sm m-2">
    <legend class="text-muted"> <small>Please pick sensor and reading</small> </legend>
        <form action="{% url 'map:historical' %}" method="GET">
          <div class="form-group row">
            <label class="col-sm-6 col-form-label" for="sensor">Sensor</label>
            <div class="col-sm-6">
                <select class="custom-select shadow-sm mt-2" name="sensor" id="sensor" required>
                    <option value="sensor_8">Sensor 8</option>
                    <option value="sensor_9">Sensor 9</option>
                    <option value="sensor_10">Sensor 10</option>
                    <option value="sensor_11">Sensor 11</option>
                    <option value="sensor_12">Sensor 12</option>
                    <option value="sensor_13">Sensor 13</option>
                    <option value="sensor_14">Sensor 14</option>
                </select>
          </div>
          </div>

          <div class="form-group row">
            <label class="col-sm-6 col-form-label" for="reading">Reading</label>
            <div class="col-sm-6">
                <select class="custom-select shadow-sm mt-2" name="reading" id="reading" required>
                    <option value="temperature">Temperature</option>
                    <option value="pressure">Pressure</option>
                    <option value="steam_injection">Steam Injection</option>
                    
                </select>
          </div>
          </div>
            <input type="submit" class="btn btn-sm shadow-sm btn-success my-2" value="Submit">
        </form>
        {% if no_reading_message_to_client %}
        <p class="display-6 text-primary">
          {{no_reading_message_to_client}}</p>
{% endif %}
        </div>
</div> <!-- row -->
  
<div class="row justify-content-center">
<div class="col-md-12 shadow-lg border border-info rounded p-4 m-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between shadow"> <span class="text-primary"><small><strong>INDUSTRIAL SITE</strong></small>
        </span>
  
        <span>
          <i class="bi bi-geo-alt-fill text-primary" style="font-size: 1.5rem;"></i>
        </span>
      </li>
      <li class="list-group-item">
        {{ map|safe}}
      </li>
    </ul>
</div>

</div> <!-- row -->

</div> <!-- main container -->

{% endblock %}

map/templates/map/home.html
{% extends 'map/base.html' %}


{% block title %}
<title>Map Home</title>
{% endblock %}

{% block content %}

<div class="container text-center mt-4">

  <div class="row justify-content-center">
    <div class="col-md-12 d-flex justify-content-between">
      <span><p class="display-6 text-primary">Industrial Site Geospatial Data</p></span>
      <span><a class="btn btn-primary shadow" href="{% url 'map:livedata' 'live' %}">
        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
        Click for Latest Data</a></span>
    </div>
  </div> <!-- row -->
 
 <hr>

<div class="row d-flex mt-5 justify-content-center p-1 bg-light">
  <div class="col-md-4 border bg-white shadow-sm m-2">
    <legend class="text-muted"> <small>Please pick date to get readings</small> </legend>
        <form action="{% url 'map:home' %}" method="GET">
          <div class="form-group row">
            <label class="col-md-4 col-form-label" for="day">Day</label>
            <div class="col-md-8">
          <input type="date" class="form-control shadow-sm" name="day" id="day" required>
          {% if no_reading_message_to_client %}
          <span class="help-block sm text-primary mt-2"><small>{{no_reading_message_to_client}}</small></span>
{% endif %}
          </div>
          </div>

          <div class="form-group row">
            <label class="col-sm-6 col-form-label" for="aggregation">Aggregation</label>
            <div class="col-sm-6">
                <select class="custom-select shadow-sm mt-2" name="aggregation" id="aggregation" required>
                    <option value="average">Average</option>
                    <option value="maximum">Maximum</option>
                    
                </select>
          </div>
          </div>
            <input type="submit" class="btn btn-sm shadow-sm btn-primary my-2" value="Submit">
        </form>
        </div>
</div> <!-- row -->
  
<div class="row justify-content-center">
<div class="col-md-12 shadow-lg border border-info rounded p-4 m-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between shadow"> <span class="text-primary"><small><strong>INDUSTRIAL SITE</strong></small>
        </span>
        <span>
          <i class="bi bi-geo-alt-fill text-primary" style="font-size: 1.5rem;"></i>
        </span>
      </li>
      <li class="list-group-item">
        {{ map|safe}}
      </li>
    </ul>
</div>
</div> <!-- row -->

 </div> <!-- main container -->

{% endblock %}

map/templates/map/livesignal.html
{% extends 'map/base.html' %}


{% block title %}
<title>Map Home</title>
{% endblock %}

{% block content %}

<div class="container text-center mt-4">
  <div class="row justify-content-center">
    <div class="col-md-12 d-flex justify-content-between">
      <span><p class="display-6 text-primary">Industrial Site Live Data</p></span>
      <span>
        <p>Last Update:
          <span id="latest"></span> | Updates in <span id="countdown"></span> seconds <span class="spinner-grow spinner-grow text-warning" role="status" aria-hidden="true"></span></p>

      </span>

    </div>
  </div> <!-- row -->
  <hr>

<div class="row justify-content-center">
<div class="col-md-12 shadow-lg border border-info rounded p-4 m-4">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between shadow"> <span class="text-primary"><small><strong>INDUSTRIAL SITE</strong></small>
        </span>
  
        <span>
          <i class="bi bi-geo-alt-fill text-primary" style="font-size: 1.5rem;"></i>
        </span>
      </li>
      <li class="list-group-item">
        {{ map|safe}}
      </li>
    </ul>
</div>
</div> <!-- row -->

</div> <!-- main container -->

<script>
  // Here I get the `latest` and `countdown` `<div>` elements.
    const latestDiv = document.getElementById('latest');
    const countdownDiv = document.getElementById('countdown');
    
    // Here I set the initial update time.
    let lastUpdateTime = new Date();
    
    // Here I define a function to update the countdown and reload the page.
    function updateCountdownAndReload() {

      // Here I calculate the time until the next update. I set this to 10 seconds but this can be changed
      const nextUpdateTime = new Date(lastUpdateTime.getTime() + 10000);
      const now = new Date();
      const countdown = Math.floor((nextUpdateTime.getTime() - now.getTime()) / 1000);
    
      //Here I update the `countdown` `<span>` element.
      countdownDiv.innerHTML = countdown.toString();
    
      // If the countdown is less than or equal to zero, reload the page.
      if (countdown <= 0) {
        window.location.reload();
      }
    }

    


    
    // Here I start the countdown.
    setInterval(updateCountdownAndReload, 1000);
    
    // Here I send the last update time to the `latest` `<span>` element.
    latestDiv.innerHTML = lastUpdateTime.toLocaleString();
  </script>


{% endblock %}